import js from "@/assets/Home/Skills/Javascript.svg";
import ts from "@/assets/Home/Skills/Ts.svg";
import amazon from "@/assets/Home/Skills/aws.svg";
import expressjs from "@/assets/Home/Skills/express.svg";
import fig from "@/assets/Home/Skills/figma.svg";
import framermotion from "@/assets/Home/Skills/framer.svg";
import graphql from "@/assets/Home/Skills/graphql.svg";
import mongodb from "@/assets/Home/Skills/mongodb.svg";
import nextjs from "@/assets/Home/Skills/nextjs.svg";
import nodejs from "@/assets/Home/Skills/nodejs.svg";
import postgres from "@/assets/Home/Skills/postgres.svg";
import prisma from "@/assets/Home/Skills/prisma.svg";
import py from "@/assets/Home/Skills/python.svg";
import rt from "@/assets/Home/Skills/react.svg";
import rdx from "@/assets/Home/Skills/redux.svg";
import supa from "@/assets/Home/Skills/supabse.svg";
import tail from "@/assets/Home/Skills/tailwind.svg";
import vscode from "@/assets/Home/Skills/vscode.svg";
import word from "@/assets/Home/Skills/wordpress.svg";

export const typescript = ts;
export const graphQl = graphql;
export const aws = amazon;
export const express = expressjs;
export const figma = fig;
export const framer = framermotion;
export const mongo = mongodb;
export const next = nextjs;
export const node = nodejs;
export const postgresql = postgres;
export const prismaorm = prisma;
export const python = py;
export const react = rt;
export const redux = rdx;
export const javascript = js;
export const tailwind = tail;
export const vs = vscode;
export const supabase = supa;
export const wordpress = word;
